name: riverpod_reminder
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  bulleted_list: ^0.0.1+0.1a
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  get: ^4.7.2
  get_storage: ^2.1.1
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.6.1
  infinite_scroll_pagination: ^5.0.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  number_paginator: ^0.4.4
  path_url_strategy_module: ^1.0.2
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.9
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.2.2
  uuid: ^4.5.1
  validators: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  # 2.5.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: SFProText
      fonts:
        - asset: assets/San_Francisco_Pro_Text/SFProText-Regular.ttf
          weight: 400
        - asset: assets/San_Francisco_Pro_Text/SFProText-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/San_Francisco_Pro_Text/SFProText-Medium.ttf
          weight: 500
        - asset: assets/San_Francisco_Pro_Text/SFProText-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/San_Francisco_Pro_Text/SFProText-Semibold.ttf
          weight: 600
        - asset: assets/San_Francisco_Pro_Text/SFProText-SemiboldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/San_Francisco_Pro_Text/SFProText-Bold.ttf
          weight: 700
        - asset: assets/San_Francisco_Pro_Text/SFProText-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/San_Francisco_Pro_Text/SFProText-Heavy.ttf
          weight: 800
        - asset: assets/San_Francisco_Pro_Text/SFProText-HeavyItalic.ttf
          weight: 800
          style: italic
        - asset: assets/San_Francisco_Pro_Text/SFProText-Light.ttf
          weight: 300
        - asset: assets/San_Francisco_Pro_Text/SFProText-LightItalic.ttf
          weight: 300
          style: italic
